name: Build

on:
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'

env:
  K8S_PATH: ./k8s/app
  # For private registry
  # IMAGE_NAME: dotnet-sample
  # For DockerHub
  IMAGE_NAME: wprmdev/dotnet-sample


jobs:
  build-and-tag:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      id-token: write
      packages: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.REGISTRY_URL }}
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:latest
            ${{ env.IMAGE_NAME }}:${{ github.ref_name }}

      - name: Update deployment.yaml with new image tag
        run: |
          sed -i 's#image: .*$#image: ${{ env.IMAGE_NAME }}:${{ github.ref_name }}#' ${{ env.K8S_PATH }}/deployment.yaml

      - name: Commit updated manifest
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add ${{ env.K8S_PATH }}/deployment.yaml
          git commit -m "chore(ci): update image ${{ env.IMAGE_NAME }} to ${{ github.ref_name }}" || echo "No changes to commit"
          git push origin main
